### ISSUE TITLE
Binary Inputs not being imported

### ISSUE THREAD

**Issue by mikihacia** [Bepacom-Raalte/bepacom-custom_components#1]
Hi,

I've got a setup of Siemens PXC.100-E controller and managed to get your HASS addon running successfully. The integration seems to be working okay, apart from the Binary Inputs not being detected.  I can see them in the addon's WebUI, but they don't seem to be going through the integration.

See log from the WebUI:

  | binaryInput:7 | objectIdentifier | binaryInput,7
  |   | objectName | AS01'Heating'Corr'RoomD
  |   | description | Corridor Demand
  |   | presentValue | inactive
  |   | statusFlags | 0,0,0,0
  |   | outOfService | false
  |   | eventState | normal
  |   | reliability | noFaultDetected
  |   | notificationClass | 32
  | binaryInput:8 | objectIdentifier | binaryInput,8
  |   | objectName | AS01'Heating'Living'RoomD
  |   | description | Living Room Demand
  |   | presentValue | inactive
  |   | statusFlags | 0,0,0,0
  |   | outOfService | false
  |   | eventState | normal
  |   | reliability | noFaultDetected
  |   | notificationClass | 32
  | binaryInput:9 | objectIdentifier | binaryInput,9
  |   | objectName | AS01'Heating'MBed'RoomD
  |   | description | Master Bedroom Demand
  |   | presentValue | inactive
  |   | statusFlags | 0,0,0,0
  |   | outOfService | false
  |   | eventState | normal
  |   | reliability | noFaultDetected
  |   | notificationClass | 32

I do have a custom units on these blocks if that matters.

Great piece of work, guys!

**Comment by Bepacom-Raalte** [comment]
Do the Home Assistant logs say anything about problems during setting up the integration? Usually if it fails, there'll be some error explaining what went wrong. You can find it in Home Assistant at Settings>System>Logs. If it's there, could you paste it here?

**Comment by Bepacom-Raalte** [comment]
Nevermind! I found the issue... I wrote .objectType instead of .objectIdentifier[0], so it never got detected. Should be fixed now if you download the integration again!
