### ISSUE TITLE
Need more detailed instructions

### ISSUE THREAD

**Issue by Bagunda** [Bepacom-Raalte/bepacom-custom_components#10]
I receive data through your add-on's web interface. How can I get this data in Home Assistant? I can `t get it. It is not written anywhere and there are no examples. Can you write the instructions in a little more detail?

![image](https://github.com/Bepacom-Raalte/bepacom-custom_components/assets/16766521/c65c3c17-8c28-409b-91e1-2e1163adff10)

**Comment by GravySeal** [comment]
Hello @Bagunda,

The next step is to install the integration, which can be found in this repository. 

In the Config folder of your home assistant, you have to create a custom_components folder.

In this folder, you paste the bacnet_interface folder which you can find here:
https://github.com/Bepacom-Raalte/bepacom-custom_components/tree/main/custom_components/bacnet_interface

Then, restart Home Assistant and manually add the integration through Settings > Devices & Services > + Add Integration and search for "BACnet".

When the integration installs, you'll have to type an IP address. Use 127.0.0.1, or any other IP address you know the BACnet add-on is running on.

Please let me know if you still have difficulties.

**Comment by Bagunda** [comment]
@GravySeal 
Clicking the link https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https://github.com/GravySeal/bepacom-repo works like magic and everything installed itself and started working.
You must indicate in the instructions which IP address we need to enter.
Typically we need to enter network parameters like 192.168.0.0/24.
But in this integration we need to enter the exact IP address that is on the interface. For example 192.168.0.42/24.
This is not quite obvious.
Thank you for such work!
True, there is still a lot to work on, but this is the best at the moment!

**Comment by GravySeal** [comment]
The reason for the subscription page is mostly to give some tools to debug the connection and play around a little bit. I am planning on making some things configurable in the add-on settings like what automatically gets subscribed to etc. A page like this would then allow you to add or remove subscriptions while the add-on is running in case you forgot things. There is still a lot that can be improved 😉
