### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ictforum-nl** [Bepacom-Raalte/bepacom-custom_components#11]
Hi, 
sinds 2 dagen loop ik tegen een nieuwe foutmelding aan.

Deze foutmelding komt een aantal keer voor in het logboek, voor binary_sensor, sensor, number, select en switch.
alle entities zijn nu niet beschikbaar.
ik draai de development add-on en de laatste integration.

Logger: homeassistant.components.binary_sensor
Source: custom_components/bacnet_interface/binary_sensor.py:36
Integration: Binaire sensor (documentation, issues)
First occurred: 09:51:41 (1 occurrences)
Last logged: 09:51:41

Error while setting up bacnet_interface platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bacnet_interface/binary_sensor.py", line 36, in async_setup_entry
    coordinator.data.devices[deviceid].objects[objectid].objectIdentifier[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by GravySeal** [comment]
Doet de normale versie hetzelfde?

**Comment by ictforum-nl** [comment]
dat weet ik niet, ik draai de dev versie omdat ik een eerder issue had. ik zie ook dat er 5 dagen geleden iets is aangepast aan de dev? dat is wel ongeveer het moment dat het bij mij misgaat..

**Comment by ictforum-nl** [comment]
bij de normale versie gebeurt dit:
KeyError: 'device:517'
ERROR:    An error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
ERROR:    Abort PDU error while reading device properties: device,521: segmentation-not-supported
ERROR:    exception: KeyError('device:521')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 139, in do_IAmRequest
    await self.read_object_list(device_identifier=apdu.iAmDeviceIdentifier)
  File "/usr/bin/BACnetIOHandler.py", line 256, in read_object_list
    for obj_id in self.bacnet_device_dict[f"device:{device_identifier[1]}"][
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:521'
ERROR:    An error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
ERROR:    Abort PDU error while reading device properties: device,510: segmentation-not-supported
ERROR:    exception: KeyError('device:510')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 139, in do_IAmRequest
    await self.read_object_list(device_identifier=apdu.iAmDeviceIdentifier)
  File "/usr/bin/BACnetIOHandler.py", line 256, in read_object_list
    for obj_id in self.bacnet_device_dict[f"device:{device_identifier[1]}"][
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:510'
ERROR:    An error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
ERROR:    Abort PDU error while reading device properties: device,5: no-response
ERROR:    exception: KeyError('device:5')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 139, in do_IAmRequest
    await self.read_object_list(device_identifier=apdu.iAmDeviceIdentifier)
  File "/usr/bin/BACnetIOHandler.py", line 256, in read_object_list
    for obj_id in self.bacnet_device_dict[f"device:{device_identifier[1]}"][
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:5'
ERROR:    An error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
WARNING:    Replacing with 0: device,58, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,58, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,54, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,54, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,62, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,62, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,56, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,56, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,61, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,61, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,59, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,59, analog-input,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,53, analog-input,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,53, analog-input,1, max-pres-value... Inf value: inf

**Comment by GravySeal** [comment]
Zou je de dev versie eens kunnen proberen? Ik denk dat er nu hetzelfde probleem is als bij de andere issue in de add-on repository.

**Comment by ictforum-nl** [comment]
Helaas dat geeft nog steeds de foutmelding "nonetype"

**Comment by GravySeal** [comment]
Zou je de dev versie opnieuw kunnen proberen? Eerst verwijderen, dan checken voor updates en dan opnieuw installeren. Er zijn nog een paar wijzigingen doorgevoerd die misschien helpen.

**Comment by ictforum-nl** [comment]
Hoi, de beste wensen voor 2024!
met deze laatste versie werkt het weer!, dank!

**Comment by GravySeal** [comment]
Hallo,
Jullie ook de beste wensen voor 2024! 
Fijn dat het weer werkt!
