### ISSUE TITLE
Unable to add new devices

### ISSUE THREAD

**Issue by Dwaynet86** [Bepacom-Raalte/bepacom-custom_components#12]
when trying to add a new device, the add device dialog is blank.

![bepacom](https://github.com/Bepacom-Raalte/bepacom-custom_components/assets/51888733/551c18a4-8cf3-4744-bf8d-ebd866183242)

**Comment by Bepacom-Raalte** [comment]
You're not supposed to add devices in this manner using this add-on/integration combination. If you added a new BACnet device on your network, the best way to get it on Home Assistant is to reload your integration.

**Comment by Bepacom-Raalte** [comment]
I added some error notifications to prevent this screen from popping up empty. I assume this can be closed since there hasn't been a reaction.
