### ISSUE TITLE
Select entities seem to be shifted for my Intesis/Toshiba airco device

### ISSUE THREAD

**Issue by infradom** [Bepacom-Raalte/bepacom-custom_components#3]
The indexing in the stateText strings seemed to be offset by one.
I have corrected this in my fork https://github.com/infradom/bacnet-fork ,
but as I only have one BACNET device, this may break other devices. I am not familiar enough with BacNet to know if this correction is needed for all Bacnet devices or just this device.

**Comment by Bepacom-Raalte** [comment]
It might seem to be vendor specific. On my Siemens PXC4 and Priva Blue ID C4 the StateText strings seem to be correctly displayed. On these devices the present value is basically never 0 and always 1-amount of StateText strings. 
Currently I'm only looking at MultiStateValue objects, as I don't have Input and Output as configured objects. Does your airconditioning's present value go to 0? Or was it an issue when writing to an object? 
If you're using MultiStateInputs or Outputs, this might be the issue as I haven't really tested those. I'll see if I can get some of those objects set up in my devices.

**Comment by infradom** [comment]
Thanks ! 
I am indeed using MultiState Inputs and  Outputs. These were offset by 1
The multivalue treatment seemed to be correct in your implementation, I dit not modify your code for multivalue, just cosmetic
So if you have not tested MultiStateInput and Output, it is highly likely that it is a but in your code.
My values start at 1
Shall I issue a Pull Request in this case ?

**Comment by Bepacom-Raalte** [comment]
Yeah, that is fine! It should be fixed then.

**Comment by Bepacom-Raalte** [comment]
It's merged, should be fine now!

**Comment by infradom** [comment]
Thanks !!!
