### ISSUE TITLE
into Lovelace?

### ISSUE THREAD

**Issue by calimansi** [Bepacom-Raalte/bepacom-custom_components#5]
Hello,

Great project.

I can see the values from a temp sensor in the webui.

How can I get these values into lovelace?

Thanks.

**Comment by Bepacom-Raalte** [comment]
Hello,

If you want to get these values into Lovelace, you have to install the integration.

First you put the integration in your custom components folder, then you add it at http://homeassistant.local:8123/config/integrations/dashboard

Just click the add integration button in the bottom and search for "bacnet". It'll show up and you can add it.
IP address will be filled in for you and it should work. Once it's added you can enable each data point and start using it.

**Comment by Bepacom-Raalte** [comment]
Did you manage to solve it?
