### ISSUE TITLE
Unable to add integration - Bepacom BACnet/IP Interface

### ISSUE THREAD

**Issue by ictforum-nl** [Bepacom-Raalte/bepacom-custom_components#6]
I'm unable to add the integration, every Ip adress entered fails.
Tried on a clean instance of HA but also fails.
latest HA on Vmware Vsphere, with multiple network adapters connected.
Bepacom Addon is working on the instance.

logfile:
Deze fout is ontstaan door een aangepaste integratie.

Logger: aiohttp.server
Source: custom_components/bacnet_interface/config_flow.py:92
Integration: Bepacom EcoPanel BACnet/IP Interface (documentation)
First occurred: 7 september 2023 om 11:57:34 (13 occurrences)
Last logged: 11:52:51

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bacnet_interface/config_flow.py", line 63, in async_step_user
    devicedict = await self._async_get_device(user_input[CONF_HOST])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bacnet_interface/config_flow.py", line 92, in _async_get_device
    return await interface.update()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioecopanel/aioecopanel.py", line 171, in update
    if not (data := await self.request("/apiv1/json")):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioecopanel/aioecopanel.py", line 132, in request
    raise EcoPanelError(
aioecopanel.exceptions.EcoPanelError: (500, {'message': 'Internal Server Error'})

**Comment by Bepacom-Raalte** [comment]
Could you maybe show me the logs of the add-on when you try to connect? I recommend setting the logging to info in the add-on when you do this.

**Comment by ictforum-nl** [comment]
Yes, zeker :)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 302, in app
    response = actual_response_class(content, **response_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 199, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
ValueError: Out of range float values are not JSON compliant
INFO:     None:0 - "GET /apiv1/json HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 302, in app
    response = actual_response_class(content, **response_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 199, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
ValueError: Out of range float values are not JSON compliant

**Comment by Bepacom-Raalte** [comment]
Heb je geprobeerd met IP 127.0.0.1? Normaal gesproken moet deze werken. Gebruik je toevallig Node Red of de NGINX proxy?

**Comment by ictforum-nl** [comment]
ook 127.0.0.1 lukt niet, dat geeft dezelfde foutmelding. ik heb een nieuwe HA instantie, zonder proxy, en dat lukt ook niet. ik gebruik nog geen node red. ik heb zelf het idee dat het komt doordat er meerdere netwerk interfaces zijn gekoppeld..
maar het Bacnet netwerk is een afgescheiden netwerk, dus ik moet wel 2 interfaces gebruiken..

**Comment by Bepacom-Raalte** [comment]
In Home Assistant zijn dit dan meerdere adapters? Detecteert de add-on je BACnet apparaten? In de add-on, zou je een keer een GET request kunnen uitvoeren op /apiv1/json? Dit kan via de Docs pagina op de web UI.

**Comment by ictforum-nl** [comment]
ja in HA zitten 2 adapters, 
ik zie allerlei bacnet devices, dus de addon lijkt prima te werken, ik krijg alleen de integration niet aan de gang

http://172.20.12.232:8123/api/hassio_ingress/NQxE32IBrLq1p0G6JUtsZuSNX-T1vWgqo3detpm_jSM/apiv1/json

**Comment by Bepacom-Raalte** [comment]
Wat ik denk dat het probleem is, is dat er floating point waardes met meer dan 1 cijfer achter de komma meegegeven proberen te worden via JSON. 

> "ValueError: Out of range float values are not JSON compliant"

Ik denk dat ik in de add-on deze moet afronden naar 1 cijfer achter de komma. Deze week heb ik daarvoor wel wat tijd vrij.

Ik hou je op de hoogte!

**Comment by ictforum-nl** [comment]
Super! , het zou echt heel tof zijn iets met de bacnet data te kunnen.. het is een Honeywell GBS, en die doen nogal moeilijk om data te delen..

**Comment by Bepacom-Raalte** [comment]
Even om te bevestigen, kun je zien of er toevallig NaN waardes opgehaald worden via BACnet?

**Comment by ictforum-nl** [comment]
Dat zou goed kunnen.

![2023-09-14 08_50_13-](https://github.com/Bepacom-Raalte/bepacom-custom_components/assets/107480811/839ab7e7-9c06-4896-a7c1-3d905b7d49c3)

bedoel je dan zoiets?

**Comment by Bepacom-Raalte** [comment]
Ik denk dat NaN alleen voor kan komen bij presentValue. Ken je Yet Another BACnet Explorer (YABE)? Zou jij voor mij alles uit je apparaten kunnen lezen en dit exporteren? Dan heb ik een idee welke waardes ik kan verwachten. Ik hoop morgen te kunnen testen met mijn testsetup.

**Comment by ictforum-nl** [comment]
Het gaat om best een grote omgeving (denk ik)
![image](https://github.com/Bepacom-Raalte/bepacom-custom_components/assets/107480811/870bb061-81e7-4afb-8651-f0ffab90e673)

het 3 nodes geexporteerd, ik hoop dat je daar iets mee kunt..
[RK6_C109.zip](https://github.com/Bepacom-Raalte/bepacom-custom_components/files/12616142/RK6_C109.zip)

**Comment by Bepacom-Raalte** [comment]
Ik heb een development build gepusht, zou jij daarmee eens kunnen proberen? Ik ben benieuwd of het wat verandert.

**Comment by ictforum-nl** [comment]
Hoi, met de 1.1.3 versie lukt het wel om de integration te installeren, 👍 volgens mij ziet hij ook alle nodes, de onderliggende apparaten zijn allemaal uitgeschakeld, ik moet even kijken welke ik graag wil zien in HA, daar ga ik maandag mee aan de slag...
ik heb er even een paar aangezet, en daar komen waardes op binnen. Super bedankt!!

**Comment by Bepacom-Raalte** [comment]
Top! Fijn om te horen. Ik zal de update naar de normale versie doordrukken. Ik laat alle entities inderdaad uitgeschakeld zodat je Home Assistant niet overspoeld wordt met data. Er zijn normaal gesproken een hoop punten die wij niet gebruiken. Laat mij maar weten of het verder lukt!

**Comment by ictforum-nl** [comment]
Hoi, ik loop nu toch tegen een dingetje aan,
Alles lijkt te werken, maar na een korte tijd lijkt de add on nu vast te lopen..

de interface ziet er dan zo uit:

[cid:a2304046-1e01-4f05-8290-c8310994799d]





Met vriendelijke groet,



Jos Sijtsema

Systeembeheerder ICT


________________________________
Van: Bepacom B.V. Raalte ***@***.***>
Verzonden: maandag 18 september 2023 09:05
Aan: Bepacom-Raalte/bepacom-custom_components ***@***.***>
CC: ICT Forum ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Bepacom-Raalte/bepacom-custom_components] Unable to add integration - Bepacom BACnet/IP Interface (Issue #6)


Top! Fijn om te horen. Ik zal de update naar de normale versie doordrukken. Ik laat alle entities inderdaad uitgeschakeld zodat je Home Assistant niet overspoeld wordt met data. Er zijn normaal gesproken een hoop punten die wij niet gebruiken. Laat mij maar weten of het verder lukt!

**Comment by Bepacom-Raalte** [comment]
Hoi Jos,

Ik kan helaas dit plaatje niet zien. Zou je logs van de add-on kunnen sturen en eventueel een screenshot via GitHub?
Gebruik je nu ook de gewone 1.1.3 versie of de development add-on?

**Comment by ictforum-nl** [comment]
Ik heb nu de standaard 1.1.3 versie weer draaien. de add-on stopt niet helemaal, ik heb de watchdog aanstaan. maar de waardes updaten niet meer..

**Comment by Bepacom-Raalte** [comment]
Ik zal even kijken. In het plaatje zie ik dat je Priva S10 gebruikt... daar heb ik al eerder ruzie mee gehad 😅
Ik heb helaas nooit direct met een S10 kunnen testen lokaal, dus helaas is dat probleem niet helemaal verholpen. Ik zal kijken wat ik kan doen. Het is nu inderdaad een probleem met de add-on.

**Comment by ictforum-nl** [comment]
Ik heb geen idee, het probleem is dat het Honeywell netwerk (bacnet) verder niet toegankelijk is, ik krijg verder ook niet echt informatie over die systemen.

**Comment by Bepacom-Raalte** [comment]
Ik zal eens kijken of ik een fix hiervoor kan maken. Wel apart dat dit eerst niet het geval was. Ik heb hiervoor deze week vast nog wel wat tijd voor.

**Comment by Bepacom-Raalte** [comment]
Een goedemiddag,

Ik heb er ondertussen nog geen tijd voor gehad om eraan te werken. Mogelijk kan ik nog wat tijd vinden volgende week.

**Comment by scoop643** [comment]
Ik heb ook wat problemen met het toevoegen van BACnet. Ik heb 2x een C4 controller van Priva, beide geen BACnet server. De 1e C4 controller is wel BACnet client naar een remote IO module. Remote IO module is 69 en de priva regelaar is 16. Ik zie in de logs wel 16 voorbij komen maar 69 niet. De priva controller heeft ook geen datapunten omdat hij client is. Als ik bij de addon kijk staat hij uit, ik kan hem dan starten en blijft hij lang wachten maar hij gaat niet aan. Maar bij de logs zie ik wel dat hij het e.e.a. probeert met device 16, en dus niet 69.

Kan het zijn dat hij vast loopt omdat device 16 geen BACnet objecten heeft?

DEBUG:    Reading object file,33 of device,16 during read_objects_periodically
DEBUG:    Reading object file,1 of device,16 during read_objects_periodically
DEBUG:    Reading object file,2 of device,16 during read_objects_periodically
DEBUG:    Reading object file,3 of device,16 during read_objects_periodically
DEBUG:    Reading object file,4 of device,16 during read_objects_periodically
DEBUG:    Reading object file,5 of device,16 during read_objects_periodically
DEBUG:    Reading object file,6 of device,16 during read_objects_periodically
DEBUG:    Reading object file,7 of device,16 during read_objects_periodically
DEBUG:    Reading object file,8 of device,16 during read_objects_periodically
DEBUG:    Reading object file,9 of device,16 during read_objects_periodically
DEBUG:    Reading object file,10 of device,16 during read_objects_periodically
DEBUG:    Reading object file,11 of device,16 during read_objects_periodically
DEBUG:    Reading object file,12 of device,16 during read_objects_periodically
DEBUG:    Reading object file,13 of device,16 during read_objects_periodically
DEBUG:    Reading object file,14 of device,16 during read_objects_periodically
DEBUG:    Reading object file,15 of device,16 during read_objects_periodically
DEBUG:    Reading object file,16 of device,16 during read_objects_periodically
DEBUG:    Reading object file,17 of device,16 during read_objects_periodically
DEBUG:    Reading object file,18 of device,16 during read_objects_periodically
DEBUG:    Reading object file,19 of device,16 during read_objects_periodically
DEBUG:    Reading object file,20 of device,16 during read_objects_periodically
DEBUG:    Reading object file,21 of device,16 during read_objects_periodically
DEBUG:    Reading object file,22 of device,16 during read_objects_periodically
DEBUG:    Reading object file,23 of device,16 during read_objects_periodically
DEBUG:    Reading object file,24 of device,16 during read_objects_periodically
DEBUG:    Reading object file,25 of device,16 during read_objects_periodically
DEBUG:    Reading object file,26 of device,16 during read_objects_periodically
DEBUG:    Reading object file,27 of device,16 during read_objects_periodically
DEBUG:    Reading object file,28 of device,16 during read_objects_periodically
DEBUG:    Reading object file,29 of device,16 during read_objects_periodically
DEBUG:    Reading object file,30 of device,16 during read_objects_periodically
DEBUG:    Reading object file,31 of device,16 during read_objects_periodically
DEBUG:    Reading object file,32 of device,16 during read_objects_periodically
DEBUG:    Reading object file,33 of device,16 during read_objects_periodically
DEBUG:    Reading object file,1 of device,16 during read_objects_periodically
DEBUG:    Reading object file,2 of device,16 during read_objects_periodically
DEBUG:    Reading object file,3 of device,16 during read_objects_periodically
DEBUG:    Reading object file,4 of device,16 during read_objects_periodically
DEBUG:    Reading object file,5 of device,16 during read_objects_periodically
DEBUG:    Reading object file,6 of device,16 during read_objects_periodically
DEBUG:    Reading object file,7 of device,16 during read_objects_periodically
DEBUG:    Reading object file,8 of device,16 during read_objects_periodically
DEBUG:    Reading object file,9 of device,16 during read_objects_periodically
DEBUG:    Reading object file,10 of device,16 during read_objects_periodically
DEBUG:    Reading object file,11 of device,16 during read_objects_periodically
DEBUG:    Reading object file,12 of device,16 during read_objects_periodically
DEBUG:    Reading object file,13 of device,16 during read_objects_periodically
DEBUG:    Reading object file,14 of device,16 during read_objects_periodically
DEBUG:    Reading object file,15 of device,16 during read_objects_periodically
DEBUG:    Reading object file,16 of device,16 during read_objects_periodically
DEBUG:    Reading object file,17 of device,16 during read_objects_periodically
DEBUG:    Reading object file,18 of device,16 during read_objects_periodically
DEBUG:    Reading object file,19 of device,16 during read_objects_periodically
DEBUG:    Reading object file,20 of device,16 during read_objects_periodically
DEBUG:    Reading object file,21 of device,16 during read_objects_periodically
DEBUG:    Reading object file,22 of device,16 during read_objects_periodically
DEBUG:    Reading object file,23 of device,16 during read_objects_periodically
DEBUG:    Reading object file,24 of device,16 during read_objects_periodically
DEBUG:    Reading object file,25 of device,16 during read_objects_periodically
DEBUG:    Reading object file,26 of device,16 during read_objects_periodically
DEBUG:    Reading object file,27 of device,16 during read_objects_periodically
DEBUG:    Reading object file,28 of device,16 during read_objects_periodically
DEBUG:    Reading object file,29 of device,16 during read_objects_periodically
DEBUG:    Reading object file,30 of device,16 during read_objects_periodically
DEBUG:    Reading object file,31 of device,16 during read_objects_periodically
DEBUG:    Reading object file,32 of device,16 during read_objects_periodically
DEBUG:    Reading object file,33 of device,16 during read_objects_periodically
DEBUG:    Reading object file,1 of device,16 during read_objects_periodically
DEBUG:    Reading object file,2 of device,16 during read_objects_periodically
DEBUG:    Reading object file,3 of device,16 during read_objects_periodically
DEBUG:    Reading object file,4 of device,16 during read_objects_periodically
DEBUG:    Reading object file,5 of device,16 during read_objects_periodically
DEBUG:    Reading object file,6 of device,16 during read_objects_periodically
DEBUG:    Reading object file,7 of device,16 during read_objects_periodically
DEBUG:    Reading object file,8 of device,16 during read_objects_periodically
DEBUG:    Reading object file,9 of device,16 during read_objects_periodically
DEBUG:    Reading object file,10 of device,16 during read_objects_periodically
DEBUG:    Reading object file,11 of device,16 during read_objects_periodically
DEBUG:    Reading object file,12 of device,16 during read_objects_periodically
DEBUG:    Reading object file,13 of device,16 during read_objects_periodically
DEBUG:    Reading object file,14 of device,16 during read_objects_periodically
DEBUG:    Reading object file,15 of device,16 during read_objects_periodically
DEBUG:    Reading object file,16 of device,16 during read_objects_periodically
DEBUG:    Reading object file,17 of device,16 during read_objects_periodically
DEBUG:    Reading object file,18 of device,16 during read_objects_periodically
DEBUG:    Reading object file,19 of device,16 during read_objects_periodically
DEBUG:    Reading object file,20 of device,16 during read_objects_periodically
DEBUG:    Reading object file,21 of device,16 during read_objects_periodically
DEBUG:    Reading object file,22 of device,16 during read_objects_periodically
DEBUG:    Reading object file,23 of device,16 during read_objects_periodically
DEBUG:    Reading object file,24 of device,16 during read_objects_periodically
DEBUG:    Reading object file,25 of device,16 during read_objects_periodically
DEBUG:    Reading object file,26 of device,16 during read_objects_periodically
DEBUG:    Reading object file,27 of device,16 during read_objects_periodically
DEBUG:    Reading object file,28 of device,16 during read_objects_periodically
DEBUG:    Reading object file,29 of device,16 during read_objects_periodically
DEBUG:    Reading object file,30 of device,16 during read_objects_periodically
DEBUG:    Reading object file,31 of device,16 during read_objects_periodically
DEBUG:    Reading object file,32 of device,16 during read_objects_periodically
DEBUG:    Reading object file,33 of device,16 during read_objects_periodically

**Comment by ictforum-nl** [comment]
Hoi, is er al zicht op een fix?

**Comment by Bepacom-Raalte** [comment]
Een goedemorgen,

Ik denk dat @scoop643 gelijk heeft en het ergens vast loopt tijdens detecteren. Ik heb er afgelopen tijd weinig tijd voor gekregen om te kijken naar een oplossing, dus heb er weinig aan kunnen doen. Hopelijk komt er binnenkort wat tijd vrij om hier aan te werken.

**Comment by Bepacom-Raalte** [comment]
> Hoeveel tijd zou je nodig hebben denk je? wellicht kunnen wij die uren inkopen?

**Comment by ictforum-nl** [comment]
hoi, de dev versie lijkt in elk geval te werken, ik heb daar we de binary sensors etc nu eerst uitgezet (alleen de analogs staan aan)
ik heb nu weer waardes in de integratie zitten.

**Comment by Bepacom-Raalte** [comment]
Zijn er verder nog problemen?

**Comment by scoop643** [comment]
Ik ben weer terug naar modbus gegaan dus ik kan het niet meer testen.

**Comment by ictforum-nl** [comment]
Bij mij lijkt het goed te werken.

**Comment by Bepacom-Raalte** [comment]
Top, dan sluit ik de issue voor nu!
